source "http://rubygems.org"
gem 'sinatra', :require => 'sinatra/base'
gem 'bson'
gem 'mongoid'
gem 'rmagick', :require => 'rvg/rvg'
gem 'haml'
gem 'rdiscount'
gem 'omniauth-vkontakte'
gem 'sinatra-flash', :require => 'sinatra/flash'
gem 'sinatra-r18n', :require => 'sinatra/r18n'